version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    image: chumatori/backend_course:current
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
      - sidekiq
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true

  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'

  sidekiq:
    image: chumatori/backend_course:current
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
volumes:
  db_data: